//go:build go1.22

// Package p2pcontract provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package p2pcontract

import (
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for BodyTooLargeErrorCode.
const (
	FSTERRCTPBODYTOOLARGE BodyTooLargeErrorCode = "FST_ERR_CTP_BODY_TOO_LARGE"
)

// Valid indicates whether the value is a known member of the BodyTooLargeErrorCode enum.
func (e BodyTooLargeErrorCode) Valid() bool {
	switch e {
	case FSTERRCTPBODYTOOLARGE:
		return true
	default:
		return false
	}
}

// Defines values for BodyTooLargeErrorError.
const (
	PayloadTooLarge BodyTooLargeErrorError = "Payload Too Large"
)

// Valid indicates whether the value is a known member of the BodyTooLargeErrorError enum.
func (e BodyTooLargeErrorError) Valid() bool {
	switch e {
	case PayloadTooLarge:
		return true
	default:
		return false
	}
}

// Defines values for BodyTooLargeErrorMessage.
const (
	RequestBodyIsTooLarge BodyTooLargeErrorMessage = "Request body is too large"
)

// Valid indicates whether the value is a known member of the BodyTooLargeErrorMessage enum.
func (e BodyTooLargeErrorMessage) Valid() bool {
	switch e {
	case RequestBodyIsTooLarge:
		return true
	default:
		return false
	}
}

// Defines values for BodyTooLargeErrorStatusCode.
const (
	N413 BodyTooLargeErrorStatusCode = 413
)

// Valid indicates whether the value is a known member of the BodyTooLargeErrorStatusCode enum.
func (e BodyTooLargeErrorStatusCode) Valid() bool {
	switch e {
	case N413:
		return true
	default:
		return false
	}
}

// Defines values for CreateRoomRequestMaxPeers.
const (
	CreateRoomRequestMaxPeersN2 CreateRoomRequestMaxPeers = 2
)

// Valid indicates whether the value is a known member of the CreateRoomRequestMaxPeers enum.
func (e CreateRoomRequestMaxPeers) Valid() bool {
	switch e {
	case CreateRoomRequestMaxPeersN2:
		return true
	default:
		return false
	}
}

// Defines values for CreatedRoomMaxPeers.
const (
	CreatedRoomMaxPeersN2 CreatedRoomMaxPeers = 2
)

// Valid indicates whether the value is a known member of the CreatedRoomMaxPeers enum.
func (e CreatedRoomMaxPeers) Valid() bool {
	switch e {
	case CreatedRoomMaxPeersN2:
		return true
	default:
		return false
	}
}

// Defines values for JSONParserErrorCode.
const (
	FSTERRCTPEMPTYJSONBODY   JSONParserErrorCode = "FST_ERR_CTP_EMPTY_JSON_BODY"
	FSTERRCTPINVALIDJSONBODY JSONParserErrorCode = "FST_ERR_CTP_INVALID_JSON_BODY"
)

// Valid indicates whether the value is a known member of the JSONParserErrorCode enum.
func (e JSONParserErrorCode) Valid() bool {
	switch e {
	case FSTERRCTPEMPTYJSONBODY:
		return true
	case FSTERRCTPINVALIDJSONBODY:
		return true
	default:
		return false
	}
}

// Defines values for JSONParserErrorError.
const (
	BadRequest JSONParserErrorError = "Bad Request"
)

// Valid indicates whether the value is a known member of the JSONParserErrorError enum.
func (e JSONParserErrorError) Valid() bool {
	switch e {
	case BadRequest:
		return true
	default:
		return false
	}
}

// Defines values for JSONParserErrorMessage.
const (
	BodyCannotBeEmptyWhenContentTypeIsSetToapplicationjson JSONParserErrorMessage = "Body cannot be empty when content-type is set to 'application/json'"
	BodyIsNotValidJSONButContentTypeIsSetToapplicationjson JSONParserErrorMessage = "Body is not valid JSON but content-type is set to 'application/json'"
)

// Valid indicates whether the value is a known member of the JSONParserErrorMessage enum.
func (e JSONParserErrorMessage) Valid() bool {
	switch e {
	case BodyCannotBeEmptyWhenContentTypeIsSetToapplicationjson:
		return true
	case BodyIsNotValidJSONButContentTypeIsSetToapplicationjson:
		return true
	default:
		return false
	}
}

// Defines values for JSONParserErrorStatusCode.
const (
	N400 JSONParserErrorStatusCode = 400
)

// Valid indicates whether the value is a known member of the JSONParserErrorStatusCode enum.
func (e JSONParserErrorStatusCode) Valid() bool {
	switch e {
	case N400:
		return true
	default:
		return false
	}
}

// Defines values for RoomStatusMaxPeers.
const (
	RoomStatusMaxPeersN2 RoomStatusMaxPeers = 2
)

// Valid indicates whether the value is a known member of the RoomStatusMaxPeers enum.
func (e RoomStatusMaxPeers) Valid() bool {
	switch e {
	case RoomStatusMaxPeersN2:
		return true
	default:
		return false
	}
}

// BodyTooLargeError defines model for BodyTooLargeError.
type BodyTooLargeError struct {
	Code       BodyTooLargeErrorCode       `json:"code"`
	Error      BodyTooLargeErrorError      `json:"error"`
	Message    BodyTooLargeErrorMessage    `json:"message"`
	StatusCode BodyTooLargeErrorStatusCode `json:"statusCode"`
}

// BodyTooLargeErrorCode defines model for BodyTooLargeError.Code.
type BodyTooLargeErrorCode string

// BodyTooLargeErrorError defines model for BodyTooLargeError.Error.
type BodyTooLargeErrorError string

// BodyTooLargeErrorMessage defines model for BodyTooLargeError.Message.
type BodyTooLargeErrorMessage string

// BodyTooLargeErrorStatusCode defines model for BodyTooLargeError.StatusCode.
type BodyTooLargeErrorStatusCode int

// CreateRoomRequest defines model for CreateRoomRequest.
type CreateRoomRequest struct {
	MaxPeers             CreateRoomRequestMaxPeers `json:"maxPeers"`
	AdditionalProperties map[string]interface{}    `json:"-"`
}

// CreateRoomRequestMaxPeers defines model for CreateRoomRequest.MaxPeers.
type CreateRoomRequestMaxPeers int

// CreatedRoom defines model for CreatedRoom.
type CreatedRoom struct {
	ExpiresAt  time.Time           `json:"expiresAt"`
	InviteLink string              `json:"inviteLink"`
	MaxPeers   CreatedRoomMaxPeers `json:"maxPeers"`
	RoomId     string              `json:"roomId"`
}

// CreatedRoomMaxPeers defines model for CreatedRoom.MaxPeers.
type CreatedRoomMaxPeers int

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	AppVersion string      `json:"appVersion"`
	Lane       interface{} `json:"lane"`
	Ok         interface{} `json:"ok"`
	Service    interface{} `json:"service"`
}

// IceServer defines model for IceServer.
type IceServer struct {
	Credential *string        `json:"credential,omitempty"`
	Urls       IceServer_Urls `json:"urls"`
	Username   *string        `json:"username,omitempty"`
}

// IceServerUrls0 defines model for IceServer.Urls.0.
type IceServerUrls0 = string

// IceServerUrls1 defines model for IceServer.Urls.1.
type IceServerUrls1 = []string

// IceServer_Urls defines model for IceServer.Urls.
type IceServer_Urls struct {
	union json.RawMessage
}

// JSONParserError defines model for JSONParserError.
type JSONParserError struct {
	Code       JSONParserErrorCode       `json:"code"`
	Error      JSONParserErrorError      `json:"error"`
	Message    JSONParserErrorMessage    `json:"message"`
	StatusCode JSONParserErrorStatusCode `json:"statusCode"`
}

// JSONParserErrorCode defines model for JSONParserError.Code.
type JSONParserErrorCode string

// JSONParserErrorError defines model for JSONParserError.Error.
type JSONParserErrorError string

// JSONParserErrorMessage defines model for JSONParserError.Message.
type JSONParserErrorMessage string

// JSONParserErrorStatusCode defines model for JSONParserError.StatusCode.
type JSONParserErrorStatusCode int

// RoomStatus defines model for RoomStatus.
type RoomStatus struct {
	ExpiresAt time.Time          `json:"expiresAt"`
	MaxPeers  RoomStatusMaxPeers `json:"maxPeers"`
	PeerCount int                `json:"peerCount"`
	RoomId    string             `json:"roomId"`
}

// RoomStatusMaxPeers defines model for RoomStatus.MaxPeers.
type RoomStatusMaxPeers int

// RoomId defines model for RoomId.
type RoomId = string

// CreateP2PRoom400JSONResponseBody defines parameters for CreateP2PRoom.
type CreateP2PRoom400JSONResponseBody struct {
	union json.RawMessage
}

// CreateP2PRoomJSONRequestBody defines body for CreateP2PRoom for application/json ContentType.
type CreateP2PRoomJSONRequestBody = CreateRoomRequest

// Getter for additional properties for CreateRoomRequest. Returns the specified
// element and whether it was found
func (a CreateRoomRequest) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for CreateRoomRequest
func (a *CreateRoomRequest) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for CreateRoomRequest to handle AdditionalProperties
func (a *CreateRoomRequest) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["maxPeers"]; found {
		err = json.Unmarshal(raw, &a.MaxPeers)
		if err != nil {
			return fmt.Errorf("error reading 'maxPeers': %w", err)
		}
		delete(object, "maxPeers")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for CreateRoomRequest to handle AdditionalProperties
func (a CreateRoomRequest) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["maxPeers"], err = json.Marshal(a.MaxPeers)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'maxPeers': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// AsIceServerUrls0 returns the union data inside the IceServer_Urls as a IceServerUrls0
func (t IceServer_Urls) AsIceServerUrls0() (IceServerUrls0, error) {
	var body IceServerUrls0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromIceServerUrls0 overwrites any union data inside the IceServer_Urls as the provided IceServerUrls0
func (t *IceServer_Urls) FromIceServerUrls0(v IceServerUrls0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeIceServerUrls0 performs a merge with any union data inside the IceServer_Urls, using the provided IceServerUrls0
func (t *IceServer_Urls) MergeIceServerUrls0(v IceServerUrls0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsIceServerUrls1 returns the union data inside the IceServer_Urls as a IceServerUrls1
func (t IceServer_Urls) AsIceServerUrls1() (IceServerUrls1, error) {
	var body IceServerUrls1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromIceServerUrls1 overwrites any union data inside the IceServer_Urls as the provided IceServerUrls1
func (t *IceServer_Urls) FromIceServerUrls1(v IceServerUrls1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeIceServerUrls1 performs a merge with any union data inside the IceServer_Urls, using the provided IceServerUrls1
func (t *IceServer_Urls) MergeIceServerUrls1(v IceServerUrls1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t IceServer_Urls) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *IceServer_Urls) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsErrorResponse returns the union data inside the CreateP2PRoom400JSONResponseBody as a ErrorResponse
func (t CreateP2PRoom400JSONResponseBody) AsErrorResponse() (ErrorResponse, error) {
	var body ErrorResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromErrorResponse overwrites any union data inside the CreateP2PRoom400JSONResponseBody as the provided ErrorResponse
func (t *CreateP2PRoom400JSONResponseBody) FromErrorResponse(v ErrorResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeErrorResponse performs a merge with any union data inside the CreateP2PRoom400JSONResponseBody, using the provided ErrorResponse
func (t *CreateP2PRoom400JSONResponseBody) MergeErrorResponse(v ErrorResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsJSONParserError returns the union data inside the CreateP2PRoom400JSONResponseBody as a JSONParserError
func (t CreateP2PRoom400JSONResponseBody) AsJSONParserError() (JSONParserError, error) {
	var body JSONParserError
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJSONParserError overwrites any union data inside the CreateP2PRoom400JSONResponseBody as the provided JSONParserError
func (t *CreateP2PRoom400JSONResponseBody) FromJSONParserError(v JSONParserError) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJSONParserError performs a merge with any union data inside the CreateP2PRoom400JSONResponseBody, using the provided JSONParserError
func (t *CreateP2PRoom400JSONResponseBody) MergeJSONParserError(v JSONParserError) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t CreateP2PRoom400JSONResponseBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *CreateP2PRoom400JSONResponseBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /api/health)
	P2pHealth(w http.ResponseWriter, r *http.Request)

	// (GET /api/p2p/ice-servers)
	GetP2PIceServers(w http.ResponseWriter, r *http.Request)

	// (POST /api/p2p/rooms)
	CreateP2PRoom(w http.ResponseWriter, r *http.Request)

	// (GET /api/p2p/rooms/{roomId})
	GetP2PRoom(w http.ResponseWriter, r *http.Request, roomId RoomId)

	// (GET /ws/p2p/{roomId})
	P2pWebSocket(w http.ResponseWriter, r *http.Request, roomId RoomId)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// P2pHealth operation middleware
func (siw *ServerInterfaceWrapper) P2pHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.P2pHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetP2PIceServers operation middleware
func (siw *ServerInterfaceWrapper) GetP2PIceServers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetP2PIceServers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateP2PRoom operation middleware
func (siw *ServerInterfaceWrapper) CreateP2PRoom(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateP2PRoom(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetP2PRoom operation middleware
func (siw *ServerInterfaceWrapper) GetP2PRoom(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "roomId" -------------
	var roomId RoomId

	err = runtime.BindStyledParameterWithOptions("simple", "roomId", r.PathValue("roomId"), &roomId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "roomId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetP2PRoom(w, r, roomId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// P2pWebSocket operation middleware
func (siw *ServerInterfaceWrapper) P2pWebSocket(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "roomId" -------------
	var roomId RoomId

	err = runtime.BindStyledParameterWithOptions("simple", "roomId", r.PathValue("roomId"), &roomId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "roomId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.P2pWebSocket(w, r, roomId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/health", wrapper.P2pHealth)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/p2p/rooms", wrapper.CreateP2PRoom)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/p2p/rooms/{roomId}", wrapper.GetP2PRoom)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/p2p/ice-servers", wrapper.GetP2PIceServers)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/ws/p2p/{roomId}", wrapper.P2pWebSocket)

	return m
}
