// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package presencequeries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const delete = `-- name: Delete :execrows
DELETE FROM workspace_presence_leases
WHERE space_id = $1::text
  AND user_id = $2::text
  AND connection_id = $3::text
`

type DeleteParams struct {
	SpaceID      string
	UserID       string
	ConnectionID string
}

func (q *Queries) Delete(ctx context.Context, arg DeleteParams) (int64, error) {
	result, err := q.db.Exec(ctx, delete, arg.SpaceID, arg.UserID, arg.ConnectionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const isOnline = `-- name: IsOnline :one
SELECT EXISTS (
  SELECT 1 FROM workspace_presence_leases p
  INNER JOIN users u ON u.id = p.user_id AND u.kind = 'human'
  INNER JOIN space_members sm
    ON sm.space_id = p.space_id AND sm.user_id = p.user_id
   AND sm.removed_at IS NULL
  WHERE p.space_id = $1::text
    AND p.user_id = $2::text
    AND p.lease_until > $3::timestamptz
) AS online
`

type IsOnlineParams struct {
	SpaceID string
	UserID  string
	NowAt   pgtype.Timestamptz
}

func (q *Queries) IsOnline(ctx context.Context, arg IsOnlineParams) (bool, error) {
	row := q.db.QueryRow(ctx, isOnline, arg.SpaceID, arg.UserID, arg.NowAt)
	var online bool
	err := row.Scan(&online)
	return online, err
}

const register = `-- name: Register :one
INSERT INTO workspace_presence_leases
  (space_id, user_id, connection_id, lease_until, created_at, updated_at)
SELECT $1::text, u.id, $2::text,
       $3::timestamptz, $4::timestamptz,
       $4::timestamptz
FROM users u
INNER JOIN space_members sm
  ON sm.space_id = $1::text
 AND sm.user_id = u.id
 AND sm.removed_at IS NULL
WHERE u.id = $5::text AND u.kind = 'human'
RETURNING connection_id
`

type RegisterParams struct {
	SpaceID      string
	ConnectionID string
	LeaseUntil   pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UserID       string
}

func (q *Queries) Register(ctx context.Context, arg RegisterParams) (string, error) {
	row := q.db.QueryRow(ctx, register,
		arg.SpaceID,
		arg.ConnectionID,
		arg.LeaseUntil,
		arg.CreatedAt,
		arg.UserID,
	)
	var connection_id string
	err := row.Scan(&connection_id)
	return connection_id, err
}

const renew = `-- name: Renew :execrows
UPDATE workspace_presence_leases
SET lease_until = $1::timestamptz,
    updated_at = $2::timestamptz
WHERE space_id = $3::text
  AND user_id = $4::text
  AND connection_id = $5::text
  AND lease_until > $2::timestamptz
  AND EXISTS (
    SELECT 1 FROM users u
    INNER JOIN space_members sm
      ON sm.space_id = workspace_presence_leases.space_id
     AND sm.user_id = workspace_presence_leases.user_id
     AND sm.removed_at IS NULL
    WHERE u.id = workspace_presence_leases.user_id AND u.kind = 'human'
  )
`

type RenewParams struct {
	LeaseUntil   pgtype.Timestamptz
	NowAt        pgtype.Timestamptz
	SpaceID      string
	UserID       string
	ConnectionID string
}

func (q *Queries) Renew(ctx context.Context, arg RenewParams) (int64, error) {
	result, err := q.db.Exec(ctx, renew,
		arg.LeaseUntil,
		arg.NowAt,
		arg.SpaceID,
		arg.UserID,
		arg.ConnectionID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sweepExpired = `-- name: SweepExpired :execrows
WITH expired AS (
  SELECT space_id, user_id, connection_id
  FROM workspace_presence_leases
  WHERE lease_until <= $1::timestamptz
  ORDER BY lease_until, space_id, user_id, connection_id
  LIMIT $2::integer
  FOR UPDATE SKIP LOCKED
)
DELETE FROM workspace_presence_leases p
USING expired
WHERE p.space_id = expired.space_id
  AND p.user_id = expired.user_id
  AND p.connection_id = expired.connection_id
`

type SweepExpiredParams struct {
	NowAt     pgtype.Timestamptz
	BatchSize int32
}

func (q *Queries) SweepExpired(ctx context.Context, arg SweepExpiredParams) (int64, error) {
	result, err := q.db.Exec(ctx, sweepExpired, arg.NowAt, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
