// The production palette source, reviewed from the approved V2 semantic colors.
// Runtime code imports this data only; prototype styles and scripts are not dependencies.
export type ThemeId = "original" | "grove" | "dusk" | "beige" | "minimal";
export type ColorMode = "light" | "dark";
export type SemanticColor =
  | "bg" | "surface" | "soft" | "elevated" | "text" | "muted"
  | "line" | "control" | "focus"
  | "shared" | "shared-soft" | "on-shared"
  | "direct" | "direct-soft" | "on-direct"
  | "success" | "success-soft" | "warning" | "warning-soft" | "danger" | "danger-soft"
  | "avatar-a" | "avatar-b";
export type SemanticColors = Readonly<Record<SemanticColor, string>>;
export type ThemeDefinition = Readonly<{
  name: string;
  description: string;
  light: SemanticColors;
  dark: SemanticColors;
}>;

export const THEMES ={
  "original": {
    "name": "原色",
    "description": "铜橙与青蓝，延续双轨的品牌记忆。",
    "light": {
      "bg": "#f5f7f8",
      "surface": "#ffffff",
      "soft": "#eef2f4",
      "text": "#202c32",
      "muted": "#586a74",
      "line": "#e0e7ea",
      "control": "#81919a",
      "shared": "#256b78",
      "shared-soft": "#e7f2f4",
      "on-shared": "#ffffff",
      "direct": "#a7482c",
      "direct-soft": "#fceee7",
      "on-direct": "#ffffff",
      "success": "#24714a",
      "success-soft": "#e8f5ed",
      "warning": "#825500",
      "warning-soft": "#fff5df",
      "danger": "#b52e49",
      "danger-soft": "#ffedf1",
      "focus": "#286b9d",
      "elevated": "#ffffff",
      "avatar-a": "#e5ebf5",
      "avatar-b": "#eee8f1"
    },
    "dark": {
      "bg": "#151b20",
      "surface": "#20292f",
      "soft": "#2a363e",
      "text": "#eaf1f5",
      "muted": "#a8bbc6",
      "line": "#35464f",
      "control": "#8198a5",
      "shared": "#9bd4df",
      "shared-soft": "#25414c",
      "on-shared": "#142c33",
      "direct": "#f3ad8f",
      "direct-soft": "#44302a",
      "on-direct": "#342319",
      "success": "#9cddb5",
      "success-soft": "#203e2f",
      "warning": "#efcd87",
      "warning-soft": "#423822",
      "danger": "#ffb0c0",
      "danger-soft": "#4b2b37",
      "focus": "#9bcbf5",
      "elevated": "#29353d",
      "avatar-a": "#324457",
      "avatar-b": "#463c50"
    }
  },
  "grove": {
    "name": "苔原",
    "description": "松绿与莓红，让交流有自然的温度。",
    "light": {
      "bg": "#f4f7f4",
      "surface": "#ffffff",
      "soft": "#eaf0eb",
      "text": "#27352c",
      "muted": "#596d5e",
      "line": "#dce6de",
      "control": "#7c9182",
      "shared": "#326c4f",
      "shared-soft": "#e5f2e9",
      "on-shared": "#ffffff",
      "direct": "#924567",
      "direct-soft": "#f8eaf0",
      "on-direct": "#ffffff",
      "success": "#246936",
      "success-soft": "#e6f5e8",
      "warning": "#835719",
      "warning-soft": "#fff3df",
      "danger": "#ad3540",
      "danger-soft": "#feeced",
      "focus": "#336da2",
      "elevated": "#ffffff",
      "avatar-a": "#e4ece5",
      "avatar-b": "#f1e8dd"
    },
    "dark": {
      "bg": "#171e1a",
      "surface": "#222d26",
      "soft": "#2d3c32",
      "text": "#edf3ed",
      "muted": "#afc2b1",
      "line": "#3a4c40",
      "control": "#879f8e",
      "shared": "#a3d4b1",
      "shared-soft": "#2a4837",
      "on-shared": "#203425",
      "direct": "#e5abc6",
      "direct-soft": "#482e3f",
      "on-direct": "#371f2c",
      "success": "#a3e0b4",
      "success-soft": "#263f2d",
      "warning": "#ecc791",
      "warning-soft": "#413722",
      "danger": "#ffb3b8",
      "danger-soft": "#4b2e32",
      "focus": "#9acdf5",
      "elevated": "#2b3930",
      "avatar-a": "#3b4f40",
      "avatar-b": "#4b4334"
    }
  },
  "dusk": {
    "name": "暮色",
    "description": "靛紫与赭金，安静而清楚的个性表达。",
    "light": {
      "bg": "#f6f5f9",
      "surface": "#ffffff",
      "soft": "#efedf5",
      "text": "#2d2b3d",
      "muted": "#68627b",
      "line": "#e4e0ee",
      "control": "#928aa4",
      "shared": "#645095",
      "shared-soft": "#f0ebfa",
      "on-shared": "#ffffff",
      "direct": "#8b5a22",
      "direct-soft": "#fbf1e1",
      "on-direct": "#ffffff",
      "success": "#26714c",
      "success-soft": "#eaf5ee",
      "warning": "#835713",
      "warning-soft": "#fff4df",
      "danger": "#b13051",
      "danger-soft": "#ffedf2",
      "focus": "#654f9b",
      "elevated": "#ffffff",
      "avatar-a": "#ebe5f4",
      "avatar-b": "#e5eaf2"
    },
    "dark": {
      "bg": "#1b1922",
      "surface": "#2a2635",
      "soft": "#373044",
      "text": "#f1edf7",
      "muted": "#bbb1cf",
      "line": "#4a405b",
      "control": "#a091b4",
      "shared": "#cbb6f0",
      "shared-soft": "#423458",
      "on-shared": "#302242",
      "direct": "#efc690",
      "direct-soft": "#493b2b",
      "on-direct": "#362917",
      "success": "#a4dcb8",
      "success-soft": "#293e34",
      "warning": "#f0cd95",
      "warning-soft": "#453b28",
      "danger": "#ffb1c5",
      "danger-soft": "#502d3d",
      "focus": "#cbb6fa",
      "elevated": "#352f44",
      "avatar-a": "#4b3e5d",
      "avatar-b": "#3a465d"
    }
  },
  "beige": {
    "name": "米色",
    "description": "经典系统的米白与蓝灰。",
    "light": {
      "bg": "#eeece2",
      "surface": "#faf8f0",
      "soft": "#e9e6db",
      "elevated": "#fffdf7",
      "text": "#33352f",
      "muted": "#646358",
      "line": "#d8d4c8",
      "control": "#87857b",
      "focus": "#466574",
      "shared": "#466574",
      "shared-soft": "#e3ebed",
      "on-shared": "#ffffff",
      "direct": "#82643d",
      "direct-soft": "#eee5d5",
      "on-direct": "#ffffff",
      "success": "#426c4d",
      "success-soft": "#e4ecdf",
      "warning": "#7d5d22",
      "warning-soft": "#f5ebd0",
      "danger": "#a13b3b",
      "danger-soft": "#f5e4df",
      "avatar-a": "#e0e6e6",
      "avatar-b": "#eae0ce"
    },
    "dark": {
      "bg": "#20211e",
      "surface": "#2b2c27",
      "soft": "#36372f",
      "elevated": "#373832",
      "text": "#eeece3",
      "muted": "#bcb9aa",
      "line": "#4a4c40",
      "control": "#929584",
      "focus": "#b6cbd2",
      "shared": "#b6cbd2",
      "shared-soft": "#353f40",
      "on-shared": "#252e32",
      "direct": "#d7bf98",
      "direct-soft": "#463f31",
      "on-direct": "#322c21",
      "success": "#add0ae",
      "success-soft": "#334234",
      "warning": "#e1c68e",
      "warning-soft": "#48402d",
      "danger": "#f0b0a4",
      "danger-soft": "#4a3430",
      "avatar-a": "#3b4748",
      "avatar-b": "#4b4435"
    }
  },
  "minimal": {
    "name": "极简",
    "description": "黑白灰阶与清晰的状态层次。",
    "light": {
      "bg": "#f6f8fa",
      "surface": "#ffffff",
      "soft": "#f3f4f5",
      "elevated": "#ffffff",
      "text": "#1f2328",
      "muted": "#59636e",
      "line": "#d8dee4",
      "control": "#7c858f",
      "focus": "#59636e",
      "shared": "#24292f",
      "shared-soft": "#eef0f2",
      "on-shared": "#ffffff",
      "direct": "#4f5863",
      "direct-soft": "#f4f5f7",
      "on-direct": "#ffffff",
      "success": "#1a7f37",
      "success-soft": "#eaf5ed",
      "warning": "#806000",
      "warning-soft": "#fff5da",
      "danger": "#b52a36",
      "danger-soft": "#fff0f1",
      "avatar-a": "#e7e9ec",
      "avatar-b": "#eff0f2"
    },
    "dark": {
      "bg": "#161719",
      "surface": "#212224",
      "soft": "#2b2d30",
      "elevated": "#2c2e31",
      "text": "#f0f1f2",
      "muted": "#b0b4ba",
      "line": "#404349",
      "control": "#8c949e",
      "focus": "#b5bbc3",
      "shared": "#f0f1f2",
      "shared-soft": "#303236",
      "on-shared": "#212224",
      "direct": "#b5bbc3",
      "direct-soft": "#303439",
      "on-direct": "#1f2328",
      "success": "#8fceaa",
      "success-soft": "#263b2d",
      "warning": "#e5c18b",
      "warning-soft": "#403829",
      "danger": "#ffabb5",
      "danger-soft": "#442c30",
      "avatar-a": "#3c3f44",
      "avatar-b": "#34373c"
    }
  }
} as const satisfies Readonly<Record<ThemeId, ThemeDefinition>>;

export function isThemeId(value: unknown): value is ThemeId {
  return typeof value === "string" && Object.hasOwn(THEMES, value);
}
