//go:build postgres_integration

package bots

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"sync/atomic"
	"testing"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
	platformmigrations "github.com/timestarry/duallane/apps/backend/internal/platform/migrations"
	platformpostgres "github.com/timestarry/duallane/apps/backend/internal/platform/postgres"
	"github.com/timestarry/duallane/apps/backend/internal/workspace/auth"
)

type pgBotIntegrationFixture struct {
	ctx     context.Context
	pool    *pgxpool.Pool
	service *Service
	now     time.Time
}

func newPGBotIntegrationFixture(t *testing.T) *pgBotIntegrationFixture {
	t.Helper()
	dsn := os.Getenv("TEST_DATABASE_URL")
	if dsn == "" {
		t.Skip("TEST_DATABASE_URL is not set")
	}

	ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
	t.Cleanup(cancel)
	conn, err := pgx.Connect(ctx, dsn)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = conn.Close(context.Background()) })

	schema := fmt.Sprintf("duallane_bots_%d", time.Now().UnixNano())
	identifier := pgx.Identifier{schema}.Sanitize()
	if _, err := conn.Exec(ctx, "CREATE SCHEMA "+identifier); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() {
		cleanupCtx, cleanupCancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer cleanupCancel()
		_, _ = conn.Exec(cleanupCtx, "DROP SCHEMA IF EXISTS "+identifier+" CASCADE")
	})
	if _, err := conn.Exec(ctx, "SET search_path TO "+identifier); err != nil {
		t.Fatal(err)
	}

	_, sourceFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller failed")
	}
	migrationDirectory := filepath.Clean(filepath.Join(filepath.Dir(sourceFile), "../../../../web/server/migrations"))
	if _, err := (platformmigrations.Runner{
		Beginner:  platformpostgres.NewMigrationBeginner(conn),
		Directory: migrationDirectory,
	}).Run(ctx); err != nil {
		t.Fatal(err)
	}

	now := time.Date(2026, 9, 4, 12, 34, 56, 789654321, time.UTC)
	seedPGBotIntegrationData(t, ctx, conn, now)

	poolConfig, err := pgxpool.ParseConfig(dsn)
	if err != nil {
		t.Fatal(err)
	}
	poolConfig.ConnConfig.RuntimeParams["search_path"] = schema
	pool, err := pgxpool.NewWithConfig(ctx, poolConfig)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(pool.Close)
	if err := pool.Ping(ctx); err != nil {
		t.Fatal(err)
	}

	var idSequence atomic.Int64
	idFactory := func() (string, error) {
		return fmt.Sprintf("bots-integration-%03d", idSequence.Add(1)), nil
	}
	var tokenSequence atomic.Int64
	tokenFactory := func() (string, error) {
		return BotTokenPrefix + fmt.Sprintf("%043d", tokenSequence.Add(1)), nil
	}
	return &pgBotIntegrationFixture{
		ctx: ctx, pool: pool, now: now,
		service: NewService(ServiceOptions{
			Repository:   NewPGRepository(pool, idFactory),
			SpaceID:      DefaultSpaceID,
			Now:          func() time.Time { return now },
			IDFactory:    idFactory,
			TokenFactory: tokenFactory,
		}),
	}
}

func seedPGBotIntegrationData(t *testing.T, ctx context.Context, conn *pgx.Conn, now time.Time) {
	t.Helper()
	for _, user := range []struct {
		id, login, name, role string
	}{
		{"usr_bot_owner", "bot-integration-owner", "Bot Integration Owner", "owner"},
		{"usr_bot_member", "bot-integration-member", "Bot Integration Member", "member"},
	} {
		mustExecPGBot(t, ctx, conn, `
			INSERT INTO users (id, github_login, display_name, kind, created_at)
			VALUES ($1, $2, $3, 'human', $4)
		`, user.id, user.login, user.name, now)
	}
	mustExecPGBot(t, ctx, conn, `
		INSERT INTO spaces (id, name, slug, created_by, created_at)
		VALUES ($1, 'Bot Integration', 'bot-integration', 'usr_bot_owner', $2)
	`, DefaultSpaceID, now)
	for _, user := range []struct {
		id, role string
	}{
		{"usr_bot_owner", "owner"},
		{"usr_bot_member", "member"},
	} {
		mustExecPGBot(t, ctx, conn, `
			INSERT INTO space_members (space_id, user_id, role, joined_at, removed_at)
			VALUES ($1, $2, $3, $4, NULL)
		`, DefaultSpaceID, user.id, user.role, now)
	}
	// Seed both conversation shapes needed by the direct grant and group
	// policy paths. The Bot user is added to the direct conversation after
	// creation, because its identity is generated by the service.
	mustExecPGBot(t, ctx, conn, `
		INSERT INTO conversations (id, space_id, type, title, direct_key, retention_count, created_by, created_at)
		VALUES
			('conv-bot-direct', $1, 'direct', 'Bot direct', 'bot-integration-direct', 10000, 'usr_bot_owner', $2),
			('conv-bot-group', $1, 'group', 'Bot group', NULL, 10000, 'usr_bot_owner', $2)
	`, DefaultSpaceID, now)
	mustExecPGBot(t, ctx, conn, `
		INSERT INTO conversation_members (conversation_id, user_id, joined_at, removed_at)
		VALUES ('conv-bot-direct', 'usr_bot_owner', $1, NULL), ('conv-bot-group', 'usr_bot_owner', $1, NULL)
	`, now)
}

func mustExecPGBot(t *testing.T, ctx context.Context, conn *pgx.Conn, query string, args ...any) {
	t.Helper()
	if _, err := conn.Exec(ctx, query, args...); err != nil {
		t.Fatal(err)
	}
}

func pgBotCount(t *testing.T, fixture *pgBotIntegrationFixture, query string, args ...any) int64 {
	t.Helper()
	var count int64
	if err := fixture.pool.QueryRow(fixture.ctx, query, args...).Scan(&count); err != nil {
		t.Fatal(err)
	}
	return count
}

func botBool(value bool) *bool { return &value }

func TestPGBotLifecycleUsesIsolatedSchemaAndAtomicEvidence(t *testing.T) {
	fixture := newPGBotIntegrationFixture(t)
	owner := "usr_bot_owner"
	spaceID := DefaultSpaceID

	// Two callers must still observe one active Bot. The service lock makes
	// the normal path deterministic, and the partial unique index remains the
	// database invariant for writers outside this service.
	type createResult struct {
		bot Bot
		err error
	}
	results := make(chan createResult, 2)
	for _, name := range []string{"Concurrent Bot A", "Concurrent Bot B"} {
		go func(name string) {
			bot, err := fixture.service.Create(fixture.ctx, CreateInput{
				ActorID: owner, SpaceID: spaceID, Name: name,
				Meta: auth.RequestMeta{RequestID: "bot-concurrent-create"},
			})
			results <- createResult{bot: bot, err: err}
		}(name)
	}
	var bot Bot
	var duplicateCount int
	for i := 0; i < 2; i++ {
		result := <-results
		if result.err == nil {
			bot = result.bot
			continue
		}
		if domainCode(result.err) != CodeBotAlreadyExists {
			t.Fatalf("concurrent create error = %v", result.err)
		}
		duplicateCount++
	}
	if bot.ID == "" || duplicateCount != 1 {
		t.Fatalf("concurrent create result = bot:%#v duplicates:%d", bot, duplicateCount)
	}
	if pgBotCount(t, fixture, `SELECT COUNT(*) FROM workspace_agent_bots WHERE space_id = $1 AND owner_user_id = $2 AND status <> 'deleted'`, spaceID, owner) != 1 {
		t.Fatal("owner active Bot invariant was not preserved")
	}
	if pgBotCount(t, fixture, `SELECT COUNT(*) FROM audit_logs WHERE action = 'bot.create' AND result = 'success'`) != 1 ||
		pgBotCount(t, fixture, `SELECT COUNT(*) FROM audit_logs WHERE action = 'bot.create' AND result = 'rejected' AND reason = $1`, CodeBotAlreadyExists) != 1 {
		t.Fatal("concurrent create evidence was not persisted atomically")
	}

	if bot.CreatedAt != "2026-09-04T12:34:56.789Z" || bot.Kind != "bot" || bot.AuthenticationAllowed || bot.CanJoinGroups {
		t.Fatalf("created projection = %#v", bot)
	}
	var storedKind, storedLogin string
	if err := fixture.pool.QueryRow(fixture.ctx, `SELECT kind, github_login FROM users WHERE id = $1`, bot.BotUserID).Scan(&storedKind, &storedLogin); err != nil {
		t.Fatal(err)
	}
	if storedKind != "bot" || !strings.HasPrefix(storedLogin, "__duallane_bot_bot_") {
		t.Fatalf("stored Bot identity = kind:%q login:%q", storedKind, storedLogin)
	}
	if pgBotCount(t, fixture, `SELECT COUNT(*) FROM workspace_agent_bot_settings s INNER JOIN workspace_agent_bot_limits l ON l.bot_id = s.bot_id WHERE s.bot_id = $1`, bot.ID) != 1 {
		t.Fatal("Bot settings and limits were not created")
	}

	settings, err := fixture.service.UpdateSettings(fixture.ctx, UpdateSettingsInput{
		ActorID: owner, SpaceID: spaceID, BotID: bot.ID,
		VisibilityPolicy: stringPtr(VisibilityGroups), AllowGroup: botBool(true),
		AllowedMemberIDs: stringSlicePtr([]string{owner, "usr_bot_member"}),
		Description:      stringPtr("integration description"),
		Meta:             auth.RequestMeta{RequestID: "bot-settings"},
	})
	if err != nil || settings.VisibilityPolicy != VisibilityGroups || !settings.AllowGroup || settings.Description == nil {
		t.Fatalf("updated settings = %#v, err=%v", settings, err)
	}
	if pgBotCount(t, fixture, `SELECT COUNT(*) FROM workspace_agent_bot_visibility_members WHERE bot_id = $1`, bot.ID) != 2 {
		t.Fatal("visibility member replacement was not persisted")
	}

	// Add the generated Bot user only after creation so direct conversations
	// retain exactly two active members for the repository authorization query.
	if _, err := fixture.pool.Exec(fixture.ctx, `
		INSERT INTO conversation_members (conversation_id, user_id, joined_at, removed_at)
		VALUES ('conv-bot-direct', $1, $2, NULL)
	`, bot.BotUserID, fixture.now); err != nil {
		t.Fatal(err)
	}
	directGrant, err := fixture.service.UpdateContextGrant(fixture.ctx, UpdateContextGrantInput{
		ActorID: owner, SpaceID: spaceID, BotID: bot.ID, ConversationID: "conv-bot-direct",
		AllowContext: botBool(true), MaxMessages: intPtr(25),
		Meta: auth.RequestMeta{RequestID: "bot-direct-grant"},
	})
	if err != nil || !directGrant.AllowContext || directGrant.GrantID == "" {
		t.Fatalf("direct grant = %#v, err=%v", directGrant, err)
	}

	groupPolicy, err := fixture.service.UpdateGroupPolicy(fixture.ctx, UpdateGroupPolicyInput{
		ActorID: owner, SpaceID: spaceID, BotID: bot.ID, ConversationID: "conv-bot-group",
		Status: "active", AllowContext: botBool(true), MaxMessages: intPtr(40),
		Meta: auth.RequestMeta{RequestID: "bot-group-policy"},
	})
	if err != nil || groupPolicy.Status != "active" || !groupPolicy.AllowContext || groupPolicy.GrantID == nil {
		t.Fatalf("group policy = %#v, err=%v", groupPolicy, err)
	}
	if pgBotCount(t, fixture, `SELECT COUNT(*) FROM conversation_members WHERE conversation_id = 'conv-bot-group' AND user_id = $1 AND removed_at IS NULL`, bot.BotUserID) != 1 {
		t.Fatal("active group policy did not add Bot membership")
	}
	policies, err := fixture.service.ListGroupPolicies(fixture.ctx, GroupPoliciesInput{ActorID: owner, SpaceID: spaceID, BotID: bot.ID})
	if err != nil || len(policies) != 1 || policies[0].ConversationID != "conv-bot-group" {
		t.Fatalf("group policies = %#v, err=%v", policies, err)
	}

	issued, err := fixture.service.IssueToken(fixture.ctx, IssueTokenInput{
		ActorID: owner, SpaceID: spaceID, BotID: bot.ID,
		Scopes: []string{"messages:send"}, ExpiresAt: fixture.now.Add(time.Hour).Format(time.RFC3339Nano),
		Meta: auth.RequestMeta{RequestID: "bot-token-issue"},
	})
	if err != nil || issued.Raw == "" || issued.Token.Token != "" {
		t.Fatalf("issued token = %#v, err=%v", issued, err)
	}
	var storedHash, scopesJSON string
	if err := fixture.pool.QueryRow(fixture.ctx, `SELECT token_hash, scopes_json FROM workspace_agent_bot_tokens WHERE id = $1`, issued.Token.ID).Scan(&storedHash, &scopesJSON); err != nil {
		t.Fatal(err)
	}
	if storedHash != HashBotToken(issued.Raw) || strings.Contains(storedHash, issued.Raw) || !strings.Contains(scopesJSON, "messages:send") {
		t.Fatalf("stored token material = hash:%q scopes:%q", storedHash, scopesJSON)
	}
	identity, err := fixture.service.AuthenticateToken(fixture.ctx, issued.Raw, AuthenticateOptions{SpaceID: spaceID})
	if err != nil || identity.BotID != bot.ID || identity.LastUsedAt != "2026-09-04T12:34:56.789Z" {
		t.Fatalf("token identity = %#v, err=%v", identity, err)
	}
	listed, err := fixture.service.ListTokens(fixture.ctx, ListTokensInput{ActorID: owner, SpaceID: spaceID, BotID: bot.ID})
	if err != nil || len(listed) != 1 || listed[0].Token != MaskBotToken() {
		t.Fatalf("listed tokens = %#v, err=%v", listed, err)
	}

	setup, err := fixture.service.CreateSetupSession(fixture.ctx, CreateSetupSessionInput{
		ActorID: owner, SpaceID: spaceID, BotID: bot.ID,
		RequestedScopes: []string{"messages:send"}, ConversationIDs: []string{"conv-bot-direct"},
		Meta: auth.RequestMeta{RequestID: "bot-setup-create"},
	})
	if err != nil || setup.Status != SetupStatusCreated || setup.ExpiresAt != "2026-09-04T12:44:56.789Z" {
		t.Fatalf("created setup = %#v, err=%v", setup, err)
	}
	requested, err := fixture.service.RequestSetup(fixture.ctx, RequestSetupInput{
		SetupID: setup.ID, ClientName: "integration-agent/1", ProtocolVersion: "v1",
		Capabilities: []string{"poll_setup"}, Meta: auth.RequestMeta{RequestID: "bot-setup-request"},
	})
	if err != nil || requested.Status != SetupStatusAwaitingUser || requested.ClientName == nil {
		t.Fatalf("requested setup = %#v, err=%v", requested, err)
	}
	approved, err := fixture.service.ApproveSetupSession(fixture.ctx, ApproveSetupInput{
		ActorID: owner, SpaceID: spaceID, SetupID: setup.ID,
		Scopes: []string{"messages:send"}, ConversationIDs: []string{"conv-bot-direct"},
		Meta: auth.RequestMeta{RequestID: "bot-setup-approve"},
	})
	if err != nil || approved.Status != SetupStatusApproved || len(approved.ApprovedScopes) != 1 {
		t.Fatalf("approved setup = %#v, err=%v", approved, err)
	}
	exchanged, err := fixture.service.ExchangeSetupSession(fixture.ctx, ExchangeSetupInput{
		SetupID: setup.ID, ClientName: "integration-agent/1", ProtocolVersion: "v1",
		Meta: auth.RequestMeta{RequestID: "bot-setup-exchange"},
	})
	if err != nil || exchanged.Session.Status != SetupStatusExchanged || exchanged.Token.Raw == "" {
		t.Fatalf("exchanged setup = %#v, err=%v", exchanged, err)
	}
	if _, err := fixture.service.ExchangeSetupSession(fixture.ctx, ExchangeSetupInput{SetupID: setup.ID}); domainCode(err) != CodeBotSetupNotApproved {
		t.Fatalf("replayed setup exchange error = %v", err)
	}
	var setupStatus string
	if err := fixture.pool.QueryRow(fixture.ctx, `SELECT status FROM workspace_agent_bot_setup_sessions WHERE id = $1`, setup.ID).Scan(&setupStatus); err != nil {
		t.Fatal(err)
	}
	if setupStatus != SetupStatusExchanged || pgBotCount(t, fixture, `SELECT COUNT(*) FROM workspace_agent_bot_tokens WHERE token_hash = $1`, exchanged.Token.Raw) != 0 {
		t.Fatalf("setup exchange persistence = status:%q raw-token-count:%d", setupStatus, pgBotCount(t, fixture, `SELECT COUNT(*) FROM workspace_agent_bot_tokens WHERE token_hash = $1`, exchanged.Token.Raw))
	}

	pending, err := fixture.service.CreateSetupSession(fixture.ctx, CreateSetupSessionInput{ActorID: owner, SpaceID: spaceID, BotID: bot.ID})
	if err != nil {
		t.Fatal(err)
	}
	deletionToken, err := fixture.service.IssueToken(fixture.ctx, IssueTokenInput{ActorID: owner, SpaceID: spaceID, BotID: bot.ID})
	if err != nil {
		t.Fatal(err)
	}
	if _, err := fixture.service.Pause(fixture.ctx, TransitionInput{ActorID: owner, SpaceID: spaceID, BotID: bot.ID, Meta: auth.RequestMeta{RequestID: "bot-pause"}}); err != nil {
		t.Fatal(err)
	}
	if pgBotCount(t, fixture, `SELECT COUNT(*) FROM workspace_agent_bot_setup_sessions WHERE id = $1 AND status = 'revoked'`, pending.ID) != 1 {
		t.Fatal("pause did not revoke pending setup")
	}
	if _, err := fixture.service.Resume(fixture.ctx, TransitionInput{ActorID: owner, SpaceID: spaceID, BotID: bot.ID}); err != nil {
		t.Fatal(err)
	}
	if _, err := fixture.service.BeginDelete(fixture.ctx, TransitionInput{ActorID: owner, SpaceID: spaceID, BotID: bot.ID, Meta: auth.RequestMeta{RequestID: "bot-delete-request"}}); err != nil {
		t.Fatal(err)
	}
	if _, err := fixture.service.FinalizeDelete(fixture.ctx, TransitionInput{ActorID: owner, SpaceID: spaceID, BotID: bot.ID, Meta: auth.RequestMeta{RequestID: "bot-delete-complete"}}); err != nil {
		t.Fatal(err)
	}
	if pgBotCount(t, fixture, `SELECT COUNT(*) FROM workspace_agent_bot_tokens WHERE bot_id = $1 AND revoked_at IS NULL`, bot.ID) != 0 ||
		pgBotCount(t, fixture, `SELECT COUNT(*) FROM space_members WHERE space_id = $1 AND user_id = $2 AND removed_at IS NOT NULL`, spaceID, bot.BotUserID) != 1 {
		t.Fatal("delete did not revoke tokens and remove Bot membership")
	}
	if _, err := fixture.service.AuthenticateToken(fixture.ctx, deletionToken.Raw, AuthenticateOptions{}); domainCode(err) != CodeBotInvalidToken {
		t.Fatalf("deleted Bot token error = %v", err)
	}
	if pgBotCount(t, fixture, `SELECT COUNT(*) FROM audit_logs WHERE action LIKE 'bot.%' AND result = 'success'`) < 10 {
		t.Fatal("management operations did not write success audit evidence")
	}
	var requestActor *string
	if err := fixture.pool.QueryRow(fixture.ctx, `SELECT actor_user_id FROM audit_logs WHERE request_id = 'bot-setup-request'`).Scan(&requestActor); err != nil {
		t.Fatal(err)
	}
	if requestActor != nil {
		t.Fatalf("external setup request unexpectedly recorded actor %q", *requestActor)
	}
}

func stringSlicePtr(value []string) *[]string { return &value }
