package botgateway

import (
	"embed"
	"encoding/json"
	"reflect"
	"testing"

	workspacemessages "github.com/timestarry/duallane/apps/backend/internal/workspace/messages"
)

// The fixture is generated by scripts/backend/bot-message-dto-fixtures.mjs
// against the real Node route and SQLite message writer. It intentionally
// stores no token or generated database identifier.
//
//go:embed testdata/node-message-dto.json
var nodeMessageDTOFixtureFS embed.FS

type nodeMessageDTOFixture struct {
	ResponseMessageKeys   []string             `json:"responseMessageKeys"`
	ResponseMessageAuthor string               `json:"responseMessageAuthor"`
	ContentKeys           []string             `json:"contentKeys"`
	Cases                 []nodeMessageDTOCase `json:"cases"`
}

type nodeMessageDTOCase struct {
	Name     string `json:"name"`
	Response struct {
		Message json.RawMessage `json:"message"`
	} `json:"response"`
}

func TestProjectWorkspaceMessageMatchesNodeGatewayDTO(t *testing.T) {
	encoded, err := nodeMessageDTOFixtureFS.ReadFile("testdata/node-message-dto.json")
	if err != nil {
		t.Fatal(err)
	}
	var fixture nodeMessageDTOFixture
	if err := json.Unmarshal(encoded, &fixture); err != nil {
		t.Fatal(err)
	}
	if fixture.ResponseMessageAuthor != "omitted" {
		t.Fatalf("fixture author contract = %q, want omitted", fixture.ResponseMessageAuthor)
	}
	if !reflect.DeepEqual(fixture.ResponseMessageKeys, []string{"id", "conversationId", "plainText", "content", "createdAt"}) {
		t.Fatalf("fixture message keys = %#v", fixture.ResponseMessageKeys)
	}
	if !reflect.DeepEqual(fixture.ContentKeys, []string{"format", "plainText", "blocks"}) {
		t.Fatalf("fixture content keys = %#v", fixture.ContentKeys)
	}

	for _, testCase := range fixture.Cases {
		t.Run(testCase.Name, func(t *testing.T) {
			var expected map[string]any
			if err := json.Unmarshal(testCase.Response.Message, &expected); err != nil {
				t.Fatal(err)
			}
			if _, present := expected["author"]; present {
				t.Fatal("Node fixture unexpectedly contains author")
			}
			var message struct {
				ID             string                    `json:"id"`
				ConversationID string                    `json:"conversationId"`
				PlainText      string                    `json:"plainText"`
				Content        workspacemessages.Content `json:"content"`
				CreatedAt      string                    `json:"createdAt"`
			}
			if err := json.Unmarshal(testCase.Response.Message, &message); err != nil {
				t.Fatal(err)
			}
			got := projectWorkspaceMessage(workspacemessages.Message{
				ID: message.ID, ConversationID: message.ConversationID, PlainText: message.PlainText,
				Content: message.Content, CreatedAt: message.CreatedAt,
			})
			gotEncoded, err := json.Marshal(got)
			if err != nil {
				t.Fatal(err)
			}
			var actual map[string]any
			if err := json.Unmarshal(gotEncoded, &actual); err != nil {
				t.Fatal(err)
			}
			if !reflect.DeepEqual(actual, expected) {
				t.Fatalf("Go DTO = %#v, Node DTO = %#v", actual, expected)
			}
		})
	}
}
