import { DEFAULT_SPACE_ID } from "../services/db.mjs";
import {
  archiveTopic,
  closeTopic,
  createTopic,
  getTopicSummary,
  joinTopic,
  leaveTopic,
  listTopics,
  TopicError,
  TopicValidationError
} from "../services/workspace-topics.mjs";

/**
 * Register the topic/member domain routes. The topic service owns all
 * membership, visibility, state and audit policy; this module only translates
 * HTTP input/output and never emits realtime events.
 *
 * The host can provide either `service` (a small method-compatible adapter) or
 * a database. `enabled` and `ensureWorkspaceEnabled` are accepted so the host
 * can use its normal Workspace feature gate without coupling this route module
 * to the monolithic application.
 */
export function registerWorkspaceTopicRoutes(app, options = {}) {
  if (!app || typeof app.post !== "function" || typeof app.get !== "function") {
    throw new TypeError("Topic routes require a Fastify application");
  }
  const staticallyDisabled = options.enabled === false || options.ensureWorkspaceEnabled === false;
  if (!options.db && !options.service && !staticallyDisabled) {
    throw new TypeError("Topic routes require a database or service");
  }

  const service = options.service ?? (options.db ? createDatabaseTopicService(options.db) : null);
  const spaceId = options.spaceId ?? DEFAULT_SPACE_ID;
  const getActorId = options.getActorId ?? defaultActorId;
  const enabled = options.ensureWorkspaceEnabled ?? options.enabled ?? true;
  const errorHandler = options.sendError ?? sendTopicError;

  const handle = (operation, { statusCode = 200 } = {}) => async (request, reply) => {
    try {
      if (!(await isEnabled(enabled, request))) {
        return reply.code(503).send({
          error: { code: "workspace.disabled", message: "共享空间暂未开放" }
        });
      }
      const actorId = await getActorId(request);
      if (!service) {
        throw new TopicError("workspace.disabled", "共享空间暂未开放", 503);
      }
      const result = await operation({ request, actorId, spaceId });
      return statusCode === 200 ? result : reply.code(statusCode).send(result);
    } catch (error) {
      return errorHandler(reply, request, error);
    }
  };

  // Register static routes before /:topicId so "mine" is never treated as an ID.
  app.get("/api/workspace/topics/mine", handle(async ({ request, actorId, spaceId }) => {
    const query = asObject(request.query);
    return {
      topics: await service.list({
        actorId,
        spaceId,
        conversationId: query.conversationId,
        status: query.status,
        mine: true,
        request
      })
    };
  }));

  app.get("/api/workspace/topics", handle(async ({ request, actorId, spaceId }) => {
    const query = asObject(request.query);
    return {
      topics: await service.list({
        actorId,
        spaceId,
        conversationId: query.conversationId,
        status: query.status,
        mine: parseBooleanQuery(query.mine),
        request
      })
    };
  }));

  app.get("/api/workspace/conversations/:conversationId/topics", handle(async ({ request, actorId, spaceId }) => {
    const query = asObject(request.query);
    return {
      topics: await service.list({
        actorId,
        spaceId,
        conversationId: request.params?.conversationId,
        status: query.status,
        mine: parseBooleanQuery(query.mine),
        request
      })
    };
  }));

  app.post("/api/workspace/conversations/:conversationId/topics", handle(async ({ request, actorId, spaceId }) => {
    const body = requireObjectBody(request.body);
    // Do not pass a client-supplied topic ID into the domain service. Topic IDs
    // are generated by the server and are never an idempotency input.
    const input = { ...body };
    delete input.topicId;
    return {
      topic: await service.create({
        ...input,
        actorId,
        spaceId,
        conversationId: request.params?.conversationId,
        request
      })
    };
  }, { statusCode: 201 }));

  app.get("/api/workspace/topics/:topicId", handle(async ({ request, actorId, spaceId }) => ({
    topic: await service.getSummary({
      actorId,
      spaceId,
      topicId: request.params?.topicId,
      request
    })
  })));

  app.post("/api/workspace/topics/:topicId/join", handle(async ({ request, actorId, spaceId }) => ({
    topic: await service.join({
      ...asObject(request.body),
      actorId,
      spaceId,
      topicId: request.params?.topicId,
      request
    })
  })));

  app.post("/api/workspace/topics/:topicId/leave", handle(async ({ request, actorId, spaceId }) => ({
    topic: await service.leave({
      ...asObject(request.body),
      actorId,
      spaceId,
      topicId: request.params?.topicId,
      request
    })
  })));

  app.post("/api/workspace/topics/:topicId/close", handle(async ({ request, actorId, spaceId }) => ({
    topic: await service.close({
      ...asObject(request.body),
      actorId,
      spaceId,
      topicId: request.params?.topicId,
      request
    })
  })));

  app.post("/api/workspace/topics/:topicId/archive", handle(async ({ request, actorId, spaceId }) => ({
    topic: await service.archive({
      ...asObject(request.body),
      actorId,
      spaceId,
      topicId: request.params?.topicId,
      request
    })
  })));

  return service;
}

function createDatabaseTopicService(db) {
  return {
    create: ({ request, ...input }) => createTopic(db, request, input),
    list: ({ request: _request, ...input }) => listTopics(db, input),
    getSummary: ({ request: _request, ...input }) => getTopicSummary(db, input),
    join: ({ request, ...input }) => joinTopic(db, request, input),
    leave: ({ request, ...input }) => leaveTopic(db, request, input),
    close: ({ request, ...input }) => closeTopic(db, request, input),
    archive: ({ request, ...input }) => archiveTopic(db, request, input)
  };
}

async function isEnabled(enabled, request) {
  if (typeof enabled === "function") {
    return Boolean(await enabled(request));
  }
  return enabled !== false;
}

function defaultActorId(request) {
  if (request?.user?.id) return request.user.id;
  return null;
}

function asObject(value) {
  return value && typeof value === "object" && !Array.isArray(value) ? value : {};
}

function requireObjectBody(body) {
  if (!body || typeof body !== "object" || Array.isArray(body)) {
    throw new TopicValidationError("topic.body_invalid", "请求内容无效");
  }
  return body;
}

function parseBooleanQuery(value) {
  if (value === undefined || value === null || value === "") return undefined;
  if (value === true || value === "true" || value === "1") return true;
  if (value === false || value === "false" || value === "0") return false;
  throw new TopicValidationError("topic.invalid_query", "查询参数无效");
}

export function sendTopicError(reply, _request, error) {
  if (error instanceof TopicError || error?.name === "TopicError") {
    return reply.code(error.statusCode ?? 400).send({
      error: {
        code: error.code,
        message: error.message
      }
    });
  }
  return reply.code(500).send({
    error: {
      code: "internal.error",
      message: "服务暂时不可用"
    }
  });
}
